name: test
on:
  push: { branches: [main] }
  pull_request: {}
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache: false
      - run: make check
        env: { SKIP_LINT: true }
      - uses: golangci/golangci-lint-action@v7
        with: { version: "latest" }
      - run: make cov
      - uses: codecov/codecov-action@v5
        env: { CODECOV_TOKEN: "${{ secrets.CODECOV_TOKEN }}" }
  test:
    strategy: { matrix: { go-version: ["1.21", "1.22"] } }
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "${{ matrix.go-version }}"
          cache: false
      - run: make test
